apiVersion: apps/v1
kind: Deployment
metadata:
  name: refinance-model-api
  namespace: monitoring
  labels:
    app: refinance-model-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refinance-model-api
  template:
    metadata:
      labels:
        app: refinance-model-api
    spec:
      serviceAccountName: gke-workload-sa
      imagePullSecrets:
      - name: artifact-registry-secret
      containers:
      - name: refinance-model-api
        image: us-central1-docker.pkg.dev/mdepew-assets/vertex-ai-images/refinance-model:v14
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 8001
          name: metrics
        env:
        - name: PROMETHEUS_METRICS_PORT
          value: "8001"
       
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: refinance-model-api
  namespace: monitoring
  labels:
    app: refinance-model-api
spec:
  selector:
    app: refinance-model-api
  ports:
  - port: 5000
    targetPort: http
    name: http
  - port: 8001
    targetPort: metrics
    name: metrics
