apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-grafana
  namespace: prometheus
spec:
  template:
    spec:
      volumes:
        - name: ml-dashboard
          configMap:
            name: ml-monitoring-dashboard
        - name: ml-dashboard-provider
          configMap:
            name: ml-dashboard-provider
      containers:
        - name: grafana
          volumeMounts:
            - name: ml-dashboard
              mountPath: /var/lib/grafana/dashboards/ml-monitoring-dashboard.json
              subPath: ml-monitoring-dashboard.json
            - name: ml-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/provider.yaml
              subPath: provider.yaml
