server:
  persistentVolume:
    size: 8Gi
  service:
    type: ClusterIP

alertmanager:
  enabled: true
  persistentVolume:
    size: 2Gi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

pushgateway:
  enabled: false

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'loan-model-metrics'
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - monitoring
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: loan-model-api
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "8001"
            action: keep
