apiVersion: batch/v1
kind: Job
metadata:
  name: test-bigquery-write
  namespace: monitoring
spec:
  template:
    spec:
      serviceAccountName: gke-workload-sa
      containers:
      - name: test-bigquery-write
        image: us-central1-docker.pkg.dev/mdepew-assets/vertex-ai-images/refinance-model:v17
        command: ["python", "test_bigquery_write.py"]
      restartPolicy: Never
  backoffLimit: 1
