apiVersion: batch/v1
kind: Job
metadata:
  name: test-bigquery-connection
  namespace: monitoring
spec:
  template:
    spec:
      serviceAccountName: gke-workload-sa
      containers:
      - name: test-bigquery
        image: us-central1-docker.pkg.dev/mdepew-assets/vertex-ai-images/refinance-model:v16
        command: ["python", "test_bigquery.py"]
      restartPolicy: Never
  backoffLimit: 1
