groups:
- name: refinance_model_alerts
  rules:
  # Model Performance Alerts
  - alert: HighModelLatency
    expr: refinance:latency_95th_5m > 1.0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High model prediction latency"
      description: "95th percentile latency is above 1 second for 5 minutes"

  - alert: HighErrorRate
    expr: refinance:error_rate_5m > 0.05
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High prediction error rate"
      description: "Error rate is above 5% for 5 minutes"

  - alert: ModelHealthCheck
    expr: refinance_model_health == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Model health check failed"
      description: "Model health indicator is reporting unhealthy status"

  # Data Quality Alerts
  - alert: AnomalousFeatureValues
    expr: abs(delta(refinance_feature_values_sum[1h])) > 3 * stddev(refinance_feature_values_sum[24h])
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Anomalous feature values detected"
      description: "Feature values are deviating significantly from historical patterns"

  - alert: HighFeatureDrift
    expr: refinance_feature_drift > 0.2
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "High feature drift detected"
      description: "KS statistic for feature drift is above threshold"

  # System Health Alerts
  - alert: HighMemoryUsage
    expr: refinance_system_memory_usage_bytes > 1e9
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory usage is above 1GB for 5 minutes"

  - alert: PredictionVolumeDropped
    expr: rate(refinance_prediction_requests_total[5m]) < 0.1
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Low prediction volume"
      description: "Prediction request rate has dropped below 0.1 requests per second"

  # Model Output Distribution Alerts
  - alert: UnusualPredictionDistribution
    expr: |
      abs(
        rate(refinance_prediction_result_total{result="1"}[30m])
        /
        rate(refinance_prediction_requests_total[30m])
        - 0.5
      ) > 0.3
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Unusual prediction distribution"
      description: "Prediction distribution has deviated significantly from expected baseline (30% from 0.5)"

  # BigQuery Data Alerts
  - alert: DataSourceUnavailable
    expr: rate(refinance_prediction_errors_total{error_type="data_source"}[5m]) > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "BigQuery data source unavailable"
      description: "Errors accessing BigQuery data source detected"
