alertmanager:
  enabled: true
  service:
    enabled: true
    annotations: {}
    type: ClusterIP
    port: 9093

server:
  enabled: true
  service:
    enabled: true
    annotations: {}
    type: ClusterIP
    port: 9090
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  additionalScrapeConfigs:
    enabled: true
    configMapName: custom-scrape-configs  # Reference to a ConfigMap for additional scrape configs

ruleFiles:
  - 'alerting-rules.yaml'  # Path to your alerting rules file
  - 'recording-rules.yaml'  # Optional: Path to your recording rules file

# Additional configurations can go here