apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-model-api
  namespace: monitoring
  labels:
    app: loan-model-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loan-model-api
  template:
    metadata:
      labels:
        app: loan-model-api
    spec:
      containers:
      - name: loan-model-api
        image: loan-model-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 8001
          name: metrics
        env:
        - name: PROMETHEUS_METRICS_PORT
          value: "8001"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: loan-model-api
  namespace: monitoring
  labels:
    app: loan-model-api
spec:
  selector:
    app: loan-model-api
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  - name: metrics
    port: 8001
    targetPort: 8001
  type: ClusterIP
