apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-model-api
  namespace: monitoring
  labels:
    app: loan-model-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-model-api
  template:
    metadata:
      labels:
        app: loan-model-api
    spec:
      containers:
      - name: loan-model-api
        image: loan-model-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 8001
          name: metrics
        env:
        - name: PROMETHEUS_METRICS_PORT
          value: "8001"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/bigquery/credentials.json"
        - name: GOOGLE_CLOUD_PROJECT
          value: "mdepew-assets"
        volumeMounts:
        - name: bigquery-creds
          mountPath: "/etc/bigquery"
          readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: bigquery-creds
        secret:
          secretName: bigquery-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: loan-model-api
  namespace: monitoring
  labels:
    app: loan-model-api
spec:
  selector:
    app: loan-model-api
  ports:
  - port: 5000
    targetPort: http
    name: http
  - port: 8001
    targetPort: metrics
    name: metrics