apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loan-model-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: loan-model
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
