apiVersion: apps/v1
kind: Deployment
metadata:
  name: classification
  namespace: monitoring
  labels:
    app: classification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classification
  template:
    metadata:
      labels:
        app: classification
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8001"
    spec:
      containers:
      - name: classification
        image: us-central1-docker.pkg.dev/mdepew-assets/vertex-ai-images/classification:latest
        ports:
        - name: http
          containerPort: 5000
        - name: metrics
          containerPort: 8001
  

        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: classification
  namespace: monitoring
  labels:
    app: classification
spec:
  selector:
    app: classification
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: http
  - name: metrics
    port: 8001
    targetPort: metrics

