apiVersion: apps/v1
kind: Deployment
metadata:
  name: distribution-monitor
  namespace: refinance-predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distribution-monitor
  template:
    metadata:
      labels:
        app: distribution-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: gke-workload-ksa
      containers:
      - name: distribution-monitor
        image: us-central1-docker.pkg.dev/mdepew-assets/vertex-ai-images/refinance-model:latest
        command: ["python", "distribution_monitor_service.py"]
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        env:
        - name: MONITORING_INTERVAL_MINUTES
          value: "60"
        - name: WINDOW_SIZE
          value: "50"
        - name: SIGNIFICANCE_LEVEL
          value: "0.1"
        - name: N_BOOTSTRAP
          value: "500"
---
apiVersion: v1
kind: Service
metadata:
  name: distribution-monitor
  namespace: refinance-predictor
  labels:
    app: distribution-monitor
spec:
  selector:
    app: distribution-monitor
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    name: metrics
  type: ClusterIP
