apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-monitor
  namespace: refinance-predictor
  labels:
    app: model-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-monitor
  template:
    metadata:
      labels:
        app: model-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: gke-workload-ksa  # Use the existing GKE Workload Identity service account
      containers:
      - name: model-monitor
        image: us-central1-docker.pkg.dev/mdepew-assets/vertex-ai-images/refinance-model:latest
        command: ["python", "model_monitor.py"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: model-monitor
  namespace: refinance-predictor
  labels:
    app: model-monitor
spec:
  selector:
    app: model-monitor
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
