apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: refinance-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - refinance-predictor
  selector:
    matchLabels:
      app: model-monitor
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: distribution-monitor
  namespace: refinance-predictor
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - refinance-predictor
  selector:
    matchLabels:
      app: distribution-monitor
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
