apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-prometheus-rules
  namespace: monitoring
data:
  model_test.rules.yaml: |
    groups:
    - name: PredictionRate
      rules:
      - alert: HighPredictionVolume
        expr: rate(model_predictions_total[1m]) * 60 > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Predictions made are high"
          description: "test alert"
    
